### PR TITLE
Add Version Info Section

### PR DESCRIPTION
**Pull request by ProPane865**
I created a version info section in the Geyser website that will tell people what versions Geyser is compatible with.

### CODE REVIEW

**Comment by Redned235** [comment]
This information is readily available on the Geyser wiki. Adding this to the website will only add more work for us when we update to newer Minecraft versions. I already spoke to you about this so I’m not sure why you’re opening a PR ¯\\_(ツ)_/¯.

**Comment by ProPane865** [comment]
Well if you don't care for it, then I can care for it. Every website NEEDS maintenance regardless of what you have in it.

**Comment by Redned235** [comment]
> Well if you don't care for it, then I can care for it. Every website NEEDS maintenance regardless of what you have in it.

I agree, but why add more work than necessary?

**Comment by ProPane865** [comment]
> > Well if you don't care for it, then I can care for it. Every website NEEDS maintenance regardless of what you have in it.
> 
> I agree, but why add more work than necessary?

It really doesn't matter lol. Minecraft versions don't even get updated that often, so this has more advantages than disadvantages.

**Pull request closed without merging**
