### PR TITLE
Minor Improvements

### PR DESCRIPTION
**Pull request by steviebeenz**
Add Image Alts, Compact some JS, Compact some HTML.

### CODE REVIEW

**Comment by steviebeenz** [comment]
@DoctorMacc Is this something your interested in?

**Comment by Heath123** [comment]
It looks like you just removed the whitespace?
Edit: Oh, and added an image alt to the logo, which is what you said

**Comment by rtm516** [comment]
Could you update this to the latest master?

**Comment by rtm516** [comment]
Could you update this to latest master and just make it the alt tags for images, as minifying the js and HTML isn't needed for the small amount it changes and the larger impact on the readability of the source.

**Comment by rtm516** [comment]
Fixed in https://github.com/GeyserMC/GeyserSite/pull/17

**Pull request closed without merging**
