### PR TITLE
Update the UI

### PR DESCRIPTION
**Pull request by steviebeenz**
Much better UI for the website. @RednedEpic @lukeeey @rtm516 @Tim203 @SupremeMortal hope you like it.

### CODE REVIEW

**Comment by Camotoy** [comment]
Could we get a screenshot of the new UI?

**Comment by lukeeey** [comment]
**Current**
screencapture-geysermc-org-2020-06-21-14_07_53

**New**
screencapture-file-C-Users-Luke-Documents-temp-GeyserSite-index-html-2020-06-21-14_08_00

**Comment by steviebeenz** [comment]
Yes, it needs improvement and that's why it is in a draft. I will fix the
unrenderable buttons glitch.

**Comment by Camotoy** [comment]
It doesn't seem like much has changed. Should I mark this PR as a draft?

**Comment by Tim203** [comment]
AnonAlpha was working on a complete new version of the website, but I haven't heared a lot about it recently.

**Comment by Camotoy** [comment]
I'm going to close this for now since it seems like the improvements don't do much. Should you improve things further, please provide a screenshot and I will be happy to reopen!

**Pull request closed without merging**
