### PR TITLE
Final Offer(Image update lol)

### PR DESCRIPTION
**Pull request by realjaycg**

### CODE REVIEW

**Comment by Redned235** [comment]
Needs rebasing.

**Comment by realjaycg** [comment]
> Needs rebasing.

wdym by that

**Comment by Jens-Co** [comment]
> > Needs rebasing.
> 
> wdym by that

Basically your branch does not have the latest commits from main wiki and is conflicting on it. A rebase will pull the commits made in the main into your branch.

**Comment by onebeastchris** [comment]
Since this image is no longer on the website, and this PR wasn't rebased, I'm closing this. Thanks anyways!

**Pull request closed without merging**
